name: MiAtoll Kernel Build (Script Based)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison lld llvm libssl-dev libelf-dev ccache zip

      - name: Run Build Script
        run: |
          chmod +x M.sh
          ./M.sh

      - name: Upload Flashable Kernel Zip
        uses: actions/upload-artifact@v4
        with:
          name: Stormbreaker-Kernel-Zip
          path: AnyKernel/*.zip
